### ISSUE TITLE
Front Page (index) - Image slider

### ISSUE THREAD

**Issue by kkampardi** [kkampardi/metalfil#11]
Build a basic front page slider. 
Images should slide using fade in/out effect

**Comment by kkampardi** [comment]
use https://startbootstrap.com/template-overviews/full-slider/

**Comment by kkampardi** [comment]
Rady to go!

**Comment by pandoheas** [comment]
The slide effect should be soothing. Something similar to this: http://www.mkvdesign.com/

**Comment by kkampardi** [comment]
I've created a custom slider for the home page similar to the above sample.
I think I am almost there. I 've uploaded everything to the server 

Can you please review? @pandoheas

**Comment by pandoheas** [comment]
It works beautifully. I would only increase the time between the changes by few seconds (3-4)

**Comment by kkampardi** [comment]
The above commit includes small changes 
Increased the time between slides
also added  some JQuery fadein/fadeout effects for the slider

@pandoheas

**Comment by pandoheas** [comment]
Perfect!

**Comment by kkampardi** [comment]
I am closing this
