### ISSUE TITLE
Menu UI/UX

### ISSUE THREAD

**Issue by kkampardi** [kkampardi/metalfil#23]
- Change the menu colors according to the second mokup
![philip-port-det](https://cloud.githubusercontent.com/assets/8265472/20524280/6a19760a-b0c2-11e6-9472-8b737734ccb1.jpg)
- Change the font family following  @pandoheas instructions

**Comment by kkampardi** [comment]
@pandoheas could you please specify the menu color rgb codes?

**Comment by pandoheas** [comment]
Yellow-ish: #ffce4b
White: #ffffff

**Comment by kkampardi** [comment]
What about the hover colours. Bootstrap Framework by default supports hovering but if we are going to keep it we should probably change the hover color. 
Check this out here [http://fbramis.com/](url)

**Comment by pandoheas** [comment]
Page not found right now :)

**Comment by pandoheas** [comment]
The hover colour should be white as the selected words

**Comment by kkampardi** [comment]
sorry there was a typo in my url :)

**Comment by pandoheas** [comment]
"If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

**Comment by pandoheas** [comment]
The menu font is Monserat Bold:
https://fonts.google.com/specimen/Montserrat

**Comment by kkampardi** [comment]
@pandoheas i've just uploaded everything to the server

You can check out this in the demo index 
Can you please reveiw?

**Comment by pandoheas** [comment]
Good job with the new changes. The menu looks fine. We might change the thickness of the font if this is too much with the black and white images. Just mind the logo, is stretched out for some reason. Also the slashes '/'  would be perfect if they are in the middle of the space between two words. Also a small change on the menu. Could you move the upper part of the menu a tad lower (like 5 pixels)?

**Comment by pandoheas** [comment]
Forgot to mention, could you make the 'work' white as default? Just to create connection with the sub menu.

**Comment by kkampardi** [comment]
- We might change the thickness of the font if this is too much with the black and white images. 
Ok. I'll leave it as is for now and we'll decide later whether to change it or not. 

- Just mind the logo, is stretched out for some reason. 
Right now I am implementing the Bootstrap navbar for the menu which is not, as far as I can see,  flexible enough. I have second thoughts about the menu: it may be better to work on a custom menu implementation as to have the desired effect. Meanwhile it will remain as is.
 
- Also the slashes '/' would be perfect if they are in the middle of the space between two words. 
Fixed - it will be included to the next pr for this issue.

- Also a small change on the menu. Could you move the upper part of the menu a tad lower (like 5 pixels)?
Fixed - it will be included to the next pr for this issue.

**Comment by kkampardi** [comment]
- Forgot to mention, could you make the 'work' white as default? Just to create connection with the sub menu.

I am not sure this is clear to me.
I thought that the white colour marks the active menu page. That means that in the front (index) page will be no active menu option, unless we add a 'home' option.
Also what kind of connection do you have in mind between the 'work' option an the submenu?

**Comment by pandoheas** [comment]
![filippos logo](https://cloud.githubusercontent.com/assets/14330317/20604502/5f0f5078-b26f-11e6-8abf-34535b14009b.gif)

This is the logo. Can you put that instead on the original dimensions?

**Comment by pandoheas** [comment]
Regarding work:
We won't have different colour for the active links. Only on 'hover'. The default white on work will indicate that the White sub menu underneath belongs to the work view.

**Comment by pandoheas** [comment]
![fbramis_logo](https://cloud.githubusercontent.com/assets/14330317/22883044/e31878f6-f1f6-11e6-8c49-da5087b9fc5b.png)

**Comment by pandoheas** [comment]
Lets leave the footer graphic for now until we have the final web page layout
