### ISSUE TITLE
Mockups for Contact and About pages

### ISSUE THREAD

**Issue by kkampardi** [kkampardi/metalfil#27]

**Comment by kkampardi** [comment]
@pandoheas  just provided me with a contact page mockup

**Comment by kkampardi** [comment]
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/8265472/23915551/1ffceb14-08f2-11e7-9251-16b0cc8d24a9.jpeg)

**Comment by pandoheas** [comment]
![about me](https://cloud.githubusercontent.com/assets/14330317/24362663/0f809564-1316-11e7-8a59-d10c5e57de58.jpg)
![contact me](https://cloud.githubusercontent.com/assets/14330317/24362664/0f83e0f2-1316-11e7-9587-3a8bf8d89d56.jpg)


I'm sending about page along with contact. Note: In the contact I made the buttom smaller and the font bigger.

Please use :https://fonts.google.com/specimen/Dosis   (medium weight) for the text of both websites
