### ISSUE TITLE
Mockups for portfolio list page (work)

### ISSUE THREAD

**Issue by kkampardi** [kkampardi/metalfil#49]
For a start i will create an html mockup for this page.

**Comment by kkampardi** [comment]
![philip-port-det](https://cloud.githubusercontent.com/assets/8265472/22560862/bdb5c9f4-e97e-11e6-87e3-e6b15775e314.jpg)

**Comment by pandoheas** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/14330317/22594008/eccb26ca-ea29-11e6-999d-3c30f8368b73.jpg)

**Comment by kkampardi** [comment]
Cool @pandoheas. I'll go for the HTML mockup. Then we can further discuss on the effects  and any other chenges

**Comment by kkampardi** [comment]
@pandoheas  I have already upload the above changes for the UI of the work view.
I have some thoughts at this point related to the UX: I am not sure that keeping the slider as a background of this view will be very friendly for the user. As far as I can imagine in the future we may experience serious UX problems. 
Though if we keep it we I suggest that we 'd better discuss in detailed about the UX for this view

**Comment by kkampardi** [comment]
@pandoheas as an alternative we could use a background image instead. With this  practice the UI will look almost the same and we wont have to pay "an arm and a leg" :)

**Comment by pandoheas** [comment]
I would say, a plain colored background would be the best option. let's try black!

**Comment by kkampardi** [comment]
This tas seems completed, so I am closing this
