### ISSUE TITLE
UX: Work View

### ISSUE THREAD

**Issue by kkampardi** [kkampardi/metalfil#54]
Fix everything that concerns the work view

**Comment by kkampardi** [comment]
@pandoheas it would be very helpful if you could be specific about the colours and the fonts.

**Comment by pandoheas** [comment]
![capture](https://cloud.githubusercontent.com/assets/14330317/23126652/82d5b6fe-f780-11e6-8d1d-ae025c35c7ca.JPG)
Hove action should look like this

**Comment by kkampardi** [comment]
For the hover effect it would be grate if you provide me with this white image

**Comment by kkampardi** [comment]
@pandoheas  did you change the font for the submenu?

**Comment by pandoheas** [comment]
This is final version with some notes

![work](https://cloud.githubusercontent.com/assets/14330317/23219348/7ad78ce0-f927-11e6-991e-3faba8daaf09.jpg)

**Comment by kkampardi** [comment]
About the pagination: I've added the UI and the custom pager for this view. I've temporary set 3 objects per page just for demonstration for the pager. We can change this later.

**Comment by kkampardi** [comment]
![diff-image-sizes](https://cloud.githubusercontent.com/assets/8265472/23577391/8fb1a686-00c6-11e7-8f91-79a61f60c602.png)
We need to check out the display of different image sizes
