### ISSUE TITLE
Sticky nav UI/UX

### ISSUE THREAD

**Issue by kkampardi** [kkampardi/metalfil#59]

**Comment by pandoheas** [comment]
This is houw the header should look like. Also when it sticks on scrolling.

Notice the white line that creates the border with the actual gallery.

**Comment by pandoheas** [comment]
![1](https://cloud.githubusercontent.com/assets/14330317/23855401/1c621a6e-07fe-11e7-8659-3bf4918850fe.jpg)
![Uploading 2.jpg…]()

**Comment by pandoheas** [comment]
The white line should be also at the bottom of the gallery above the credits

**Comment by kkampardi** [comment]
Fix everything except the bottom white band! This is a quite tricky  UI task  I was thinking leaving it for sometime later
